package POJOs;
// Generated 13/10/2023 03:16:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private Empleado empleadoByUsuarioIngresa;
     private Empleado empleadoByUsuarioModifica;
     private Boolean estado;
     private String nombreCliente;
     private String apellidoCliente;
     private String nitCliente;
     private String telefono;
     private Date fechaIngresa;
     private Date fechaModifica;
     private Set ventas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public Cliente(int idCliente, Empleado empleadoByUsuarioIngresa, Empleado empleadoByUsuarioModifica, Boolean estado, String nombreCliente, String apellidoCliente, String nitCliente, String telefono, Date fechaIngresa, Date fechaModifica, Set ventas) {
       this.idCliente = idCliente;
       this.empleadoByUsuarioIngresa = empleadoByUsuarioIngresa;
       this.empleadoByUsuarioModifica = empleadoByUsuarioModifica;
       this.estado = estado;
       this.nombreCliente = nombreCliente;
       this.apellidoCliente = apellidoCliente;
       this.nitCliente = nitCliente;
       this.telefono = telefono;
       this.fechaIngresa = fechaIngresa;
       this.fechaModifica = fechaModifica;
       this.ventas = ventas;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public Empleado getEmpleadoByUsuarioIngresa() {
        return this.empleadoByUsuarioIngresa;
    }
    
    public void setEmpleadoByUsuarioIngresa(Empleado empleadoByUsuarioIngresa) {
        this.empleadoByUsuarioIngresa = empleadoByUsuarioIngresa;
    }
    public Empleado getEmpleadoByUsuarioModifica() {
        return this.empleadoByUsuarioModifica;
    }
    
    public void setEmpleadoByUsuarioModifica(Empleado empleadoByUsuarioModifica) {
        this.empleadoByUsuarioModifica = empleadoByUsuarioModifica;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getApellidoCliente() {
        return this.apellidoCliente;
    }
    
    public void setApellidoCliente(String apellidoCliente) {
        this.apellidoCliente = apellidoCliente;
    }
    public String getNitCliente() {
        return this.nitCliente;
    }
    
    public void setNitCliente(String nitCliente) {
        this.nitCliente = nitCliente;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Date getFechaIngresa() {
        return this.fechaIngresa;
    }
    
    public void setFechaIngresa(Date fechaIngresa) {
        this.fechaIngresa = fechaIngresa;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


