package POJOs;
// Generated 26/10/2023 04:27:11 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detalle generated by hbm2java
 */
public class Detalle  implements java.io.Serializable {


     private int idDetalle;
     private Producto producto;
     private Venta venta;
     private Integer cantidad;
     private BigDecimal precioProducto;
     private BigDecimal total;

    public Detalle() {
    }

	
    public Detalle(int idDetalle) {
        this.idDetalle = idDetalle;
    }
    public Detalle(int idDetalle, Producto producto, Venta venta, Integer cantidad, BigDecimal precioProducto, BigDecimal total) {
       this.idDetalle = idDetalle;
       this.producto = producto;
       this.venta = venta;
       this.cantidad = cantidad;
       this.precioProducto = precioProducto;
       this.total = total;
    }
   
    public int getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(int idDetalle) {
        this.idDetalle = idDetalle;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecioProducto() {
        return this.precioProducto;
    }
    
    public void setPrecioProducto(BigDecimal precioProducto) {
        this.precioProducto = precioProducto;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }




}


