package POJOs;
// Generated 13/10/2023 06:49:52 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Detalle generated by hbm2java
 */
public class Detalle  implements java.io.Serializable {


     private int idDetalle;
     private Producto producto;
     private Integer cantidad;
     private BigDecimal precioProducto;
     private Set ventas = new HashSet(0);

    public Detalle() {
    }

	
    public Detalle(int idDetalle) {
        this.idDetalle = idDetalle;
    }
    public Detalle(int idDetalle, Producto producto, Integer cantidad, BigDecimal precioProducto, Set ventas) {
       this.idDetalle = idDetalle;
       this.producto = producto;
       this.cantidad = cantidad;
       this.precioProducto = precioProducto;
       this.ventas = ventas;
    }
   
    public int getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(int idDetalle) {
        this.idDetalle = idDetalle;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecioProducto() {
        return this.precioProducto;
    }
    
    public void setPrecioProducto(BigDecimal precioProducto) {
        this.precioProducto = precioProducto;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


