package POJOs;
// Generated 27/10/2023 03:45:55 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detalle generated by hbm2java
 */
public class Detalle  implements java.io.Serializable {


     private Integer idDetalle;
     private Producto producto;
     private Venta venta;
     private Boolean estado;
     private Integer cantidad;
     private BigDecimal precioProducto;
     private BigDecimal total;

    public Detalle() {
    }

    public Detalle(Producto producto, Venta venta, Boolean estado, Integer cantidad, BigDecimal precioProducto, BigDecimal total) {
       this.producto = producto;
       this.venta = venta;
       this.estado = estado;
       this.cantidad = cantidad;
       this.precioProducto = precioProducto;
       this.total = total;
    }
   
    public Integer getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(Integer idDetalle) {
        this.idDetalle = idDetalle;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecioProducto() {
        return this.precioProducto;
    }
    
    public void setPrecioProducto(BigDecimal precioProducto) {
        this.precioProducto = precioProducto;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }




}


