package POJOs;
// Generated 26/10/2023 04:27:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private int idFactura;
     private Cliente cliente;
     private Empleado empleado;
     private Boolean estado;
     private Date fechaVenta;
     private Integer idEmpleado;
     private Date fechaIngresa;
     private Set detalles = new HashSet(0);

    public Venta() {
    }

	
    public Venta(int idFactura) {
        this.idFactura = idFactura;
    }
    public Venta(int idFactura, Cliente cliente, Empleado empleado, Boolean estado, Date fechaVenta, Integer idEmpleado, Date fechaIngresa, Set detalles) {
       this.idFactura = idFactura;
       this.cliente = cliente;
       this.empleado = empleado;
       this.estado = estado;
       this.fechaVenta = fechaVenta;
       this.idEmpleado = idEmpleado;
       this.fechaIngresa = fechaIngresa;
       this.detalles = detalles;
    }
   
    public int getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(int idFactura) {
        this.idFactura = idFactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Date getFechaIngresa() {
        return this.fechaIngresa;
    }
    
    public void setFechaIngresa(Date fechaIngresa) {
        this.fechaIngresa = fechaIngresa;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }




}


