package POJOs;
// Generated 24/10/2023 12:54:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private int idFactura;
     private Cliente cliente;
     private Detalle detalle;
     private Empleado empleadoByUsuarioIngresa;
     private Empleado empleadoByUsuarioModifica;
     private Date fechaVenta;
     private Integer idEmpleado;
     private Date fechaIngresa;
     private Date fechaModifica;

    public Venta() {
    }

	
    public Venta(int idFactura) {
        this.idFactura = idFactura;
    }
    public Venta(int idFactura, Cliente cliente, Detalle detalle, Empleado empleadoByUsuarioIngresa, Empleado empleadoByUsuarioModifica, Date fechaVenta, Integer idEmpleado, Date fechaIngresa, Date fechaModifica) {
       this.idFactura = idFactura;
       this.cliente = cliente;
       this.detalle = detalle;
       this.empleadoByUsuarioIngresa = empleadoByUsuarioIngresa;
       this.empleadoByUsuarioModifica = empleadoByUsuarioModifica;
       this.fechaVenta = fechaVenta;
       this.idEmpleado = idEmpleado;
       this.fechaIngresa = fechaIngresa;
       this.fechaModifica = fechaModifica;
    }
   
    public int getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(int idFactura) {
        this.idFactura = idFactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Detalle getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(Detalle detalle) {
        this.detalle = detalle;
    }
    public Empleado getEmpleadoByUsuarioIngresa() {
        return this.empleadoByUsuarioIngresa;
    }
    
    public void setEmpleadoByUsuarioIngresa(Empleado empleadoByUsuarioIngresa) {
        this.empleadoByUsuarioIngresa = empleadoByUsuarioIngresa;
    }
    public Empleado getEmpleadoByUsuarioModifica() {
        return this.empleadoByUsuarioModifica;
    }
    
    public void setEmpleadoByUsuarioModifica(Empleado empleadoByUsuarioModifica) {
        this.empleadoByUsuarioModifica = empleadoByUsuarioModifica;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Date getFechaIngresa() {
        return this.fechaIngresa;
    }
    
    public void setFechaIngresa(Date fechaIngresa) {
        this.fechaIngresa = fechaIngresa;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }




}


